name: heh-build
on: workflow_dispatch

jobs:
  minimal:
    runs-on: ubuntu-latest
    name: ubuntu / stable / minimal-versions
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install nightly for -Zdirect-minimal-versions
        uses: dtolnay/rust-toolchain@nightly
      - name: rustup default stable
        run: rustup default stable
      - name: cargo update -Zdirect-minimal-versions
        run: cargo +nightly update -Zdirect-minimal-versions
      - name: cargo build
        run: cargo build --release
      
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: hehInstall
          path: |
            target/release/heh
