name: heh-build
on: workflow_dispatch

jobs:
  minimal:
    runs-on: ubuntu-latest
    name: ubuntu / stable / minimal-versions
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install nightly for -Zdirect-minimal-versions
        uses: dtolnay/rust-toolchain@nightly
      - name: rustup default stable
        run: rustup default stable
      - name: cargo update -Zdirect-minimal-versions
        run: cargo +nightly update -Zdirect-minimal-versions
      - name: rustup x86_64-unknown-linux-musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: rustup toolchain add nightly-x86_64-unknown-linux-gnu
        run: rustup toolchain add nightly-x86_64-unknown-linux-gnu
      - name: rustup target add x86_64-unknown-linux-musl --toolchain=nightly
        run: rustup target add x86_64-unknown-linux-musl --toolchain=nightly
      - name: apt install musl-tools -y
        run: sudo apt-get install musl-tools -y
      - name: cargo build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: display target folder
        run: sudo apt-get install tree && tree target
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: hehInstall
          path: |
            target/x86_64-unknown-linux-musl/release/heh
